# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.0.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.0.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/alexjo/Projects/gherkin_csv/gherkin_csv

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/alexjo/Projects/gherkin_csv/gherkin_csv

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.0.0/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.0.0/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.0.0/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.0.0/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.0.0/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.0.0/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/alexjo/Projects/gherkin_csv/gherkin_csv/CMakeFiles /Users/alexjo/Projects/gherkin_csv/gherkin_csv/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/alexjo/Projects/gherkin_csv/gherkin_csv/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gherkin_csv

# Build rule for target.
gherkin_csv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gherkin_csv
.PHONY : gherkin_csv

# fast build rule for target.
gherkin_csv/fast:
	$(MAKE) -f CMakeFiles/gherkin_csv.dir/build.make CMakeFiles/gherkin_csv.dir/build
.PHONY : gherkin_csv/fast

src/csv_writer.o: src/csv_writer.c.o
.PHONY : src/csv_writer.o

# target to build an object file
src/csv_writer.c.o:
	$(MAKE) -f CMakeFiles/gherkin_csv.dir/build.make CMakeFiles/gherkin_csv.dir/src/csv_writer.c.o
.PHONY : src/csv_writer.c.o

src/csv_writer.i: src/csv_writer.c.i
.PHONY : src/csv_writer.i

# target to preprocess a source file
src/csv_writer.c.i:
	$(MAKE) -f CMakeFiles/gherkin_csv.dir/build.make CMakeFiles/gherkin_csv.dir/src/csv_writer.c.i
.PHONY : src/csv_writer.c.i

src/csv_writer.s: src/csv_writer.c.s
.PHONY : src/csv_writer.s

# target to generate assembly for a file
src/csv_writer.c.s:
	$(MAKE) -f CMakeFiles/gherkin_csv.dir/build.make CMakeFiles/gherkin_csv.dir/src/csv_writer.c.s
.PHONY : src/csv_writer.c.s

src/feature_reader.o: src/feature_reader.c.o
.PHONY : src/feature_reader.o

# target to build an object file
src/feature_reader.c.o:
	$(MAKE) -f CMakeFiles/gherkin_csv.dir/build.make CMakeFiles/gherkin_csv.dir/src/feature_reader.c.o
.PHONY : src/feature_reader.c.o

src/feature_reader.i: src/feature_reader.c.i
.PHONY : src/feature_reader.i

# target to preprocess a source file
src/feature_reader.c.i:
	$(MAKE) -f CMakeFiles/gherkin_csv.dir/build.make CMakeFiles/gherkin_csv.dir/src/feature_reader.c.i
.PHONY : src/feature_reader.c.i

src/feature_reader.s: src/feature_reader.c.s
.PHONY : src/feature_reader.s

# target to generate assembly for a file
src/feature_reader.c.s:
	$(MAKE) -f CMakeFiles/gherkin_csv.dir/build.make CMakeFiles/gherkin_csv.dir/src/feature_reader.c.s
.PHONY : src/feature_reader.c.s

src/gherkincsv.o: src/gherkincsv.c.o
.PHONY : src/gherkincsv.o

# target to build an object file
src/gherkincsv.c.o:
	$(MAKE) -f CMakeFiles/gherkin_csv.dir/build.make CMakeFiles/gherkin_csv.dir/src/gherkincsv.c.o
.PHONY : src/gherkincsv.c.o

src/gherkincsv.i: src/gherkincsv.c.i
.PHONY : src/gherkincsv.i

# target to preprocess a source file
src/gherkincsv.c.i:
	$(MAKE) -f CMakeFiles/gherkin_csv.dir/build.make CMakeFiles/gherkin_csv.dir/src/gherkincsv.c.i
.PHONY : src/gherkincsv.c.i

src/gherkincsv.s: src/gherkincsv.c.s
.PHONY : src/gherkincsv.s

# target to generate assembly for a file
src/gherkincsv.c.s:
	$(MAKE) -f CMakeFiles/gherkin_csv.dir/build.make CMakeFiles/gherkin_csv.dir/src/gherkincsv.c.s
.PHONY : src/gherkincsv.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... gherkin_csv"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... src/csv_writer.o"
	@echo "... src/csv_writer.i"
	@echo "... src/csv_writer.s"
	@echo "... src/feature_reader.o"
	@echo "... src/feature_reader.i"
	@echo "... src/feature_reader.s"
	@echo "... src/gherkincsv.o"
	@echo "... src/gherkincsv.i"
	@echo "... src/gherkincsv.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

